# Generated by Django 5.2.8 on 2025-11-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_password_register_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='phone',
            new_name='Phone',
        ),
    ]
